language: go

dist: xenial

addons:
  apt:
    packages:
    - gcc-aarch64-linux-gnu
    - g++-aarch64-linux-gnu
    - libbluetooth-dev
    - rpm
    - python3-pip
    - python3-setuptools
    - doxygen
install:
  - |
    if [ ! -f $PWD/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf ]; then
      wget https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz
      tar xf gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz
    fi
  - pip3 install --upgrade cross-sysroot
  - pip3 install Sphinx
  - pip3 install breathe
