language: go

dist: xenial

addons:
  apt:
    packages:
    - gcc-aarch64-linux-gnu
    - g++-aarch64-linux-gnu
    - libbluetooth-dev
    - rpm
    - python3-pip
    - python3-setuptools
    - doxygen
